### ISSUE TITLE
Chapter 11.2 Title Translation Error

### ISSUE THREAD

**Issue by Nimeavles** [RustLangES/rust-book-es#32]
# Title of chapter 11.2 isn't translated

I was looking for some documentation, and I've seen that `title` of the `chapters 11.2 and 11.3` aren't translated. Instead of **"Controlando como los tests son ejecutados"**, it appears **"Controling How Tests Are Run"**, and the same happends with the chapter 11.3.

![image](https://github.com/RustLangES/rust-book-es/assets/90445114/a559bebe-a002-4ca6-b96b-a85ea257618e)

## Fix
I guess that fixing it wouldn't be so difficult. Just change the title of the chapter.

**Comment by CrawKatt** [comment]
that is part of the summary.md. You have to change it there

**Comment by Nimeavles** [comment]
Ok I'll fix it and then I'll send the pr.

**Comment by Nimeavles** [comment]
fixed with #33
