### ISSUE TITLE
Apéndice C: Traits derivables

### ISSUE THREAD

**Issue by george0131** [RustLangES/rust-book-es#61]
Buenas tardes.

Encontré un párrafo repetido en la sección **Apéndice C: Traits derivables**

![image](https://github.com/RustLangES/rust-book-es/assets/4283635/559f673e-999d-459b-a883-01698ec23ba3)

**Comment by krovuxdev** [comment]
ya se elimino un parrafo repetido en PR #62 63035c8aa416
