### ISSUE TITLE
Error de traducción

### ISSUE THREAD

**Issue by pablistem** [RustLangES/rust-book-es#70]
**URL a la seccion(es) del libro con el problema:** https://book.rustlang-es.org/ch10-01-syntax

**Descripción del problema:**
En 4 primeros títulos se utiliza la preposición "in" en lugar de "en" y el último título contiene 2 palabras esdrújulas sin acentuar.
 
Definiciones in function
Definiciones in struct
Definiciones in enum
Definiciones in method
Rendimiento de codigo usando genericos 

**Cambio sugerido:**
Definiciones en function
Definiciones en struct
Definiciones en enum
Definiciones en method
Rendimiento de código usando genéricos

**Comment by Phosphorus-M** [comment]
Te animas a revisarlo? Si lo editas y armas un PR lo aceptamos

https://github.com/RustLangES/rust-book-es/edit/main/src/ch10-01-syntax.md

**Comment by pablistem** [comment]
Estoy trabajando es eso!
